# permissions for end users to view kinkmachinetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kink
    app.kubernetes.io/managed-by: kustomize
  name: infrastructure-kinkmachinetemplate-viewer-role
rules:
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - kinkmachinetemplates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - kinkmachinetemplates/status
    verbs:
      - get
