# permissions for end users to edit kinkmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kink
    app.kubernetes.io/managed-by: kustomize
  name: kinkmachine-editor-role
rules:
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - kinkmachines
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - kinkmachines/status
    verbs:
      - get
