apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KinkControlPlaneTemplate
metadata:
  labels:
    app.kubernetes.io/name: kink
    app.kubernetes.io/managed-by: kustomize
  name: kinkcontrolplanetemplate-sample
spec:
  # TODO(user): Add fields here
